"""Offline tests for the CDSE client. No network, no quota.

Every request is served by an ``httpx.MockTransport``, injected through the
``_http_client`` seam. The fixtures under ``tests/fixtures`` were captured by
hand once and trimmed; they are not regenerated by the suite.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

import httpx
import pytest

from app.core.config import settings
from app.services.acquisitions import copernicus


FIXTURES = Path(__file__).parent / "fixtures"
BBOX = copernicus.BoundingBox(west=79.5, south=12.5, east=82.5, north=15.0)
START = datetime(2026, 6, 1, tzinfo=timezone.utc)
END = datetime(2026, 7, 3, tzinfo=timezone.utc)
PRODUCT_ID = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"


def _fixture(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


@pytest.fixture(autouse=True)
def _configured_provider(monkeypatch):
    """Give every test working credentials and a clean token cache."""
    monkeypatch.setattr(settings, "COPERNICUS_ENABLED", True)
    monkeypatch.setattr(settings, "COPERNICUS_CLIENT_ID", "test-client")
    monkeypatch.setattr(settings, "COPERNICUS_CLIENT_SECRET", "test-secret")
    monkeypatch.setattr(
        settings, "COPERNICUS_ALLOWED_REDIRECT_HOSTS", ["dataspace.copernicus.eu"]
    )
    copernicus.reset_token_cache()
    yield
    copernicus.reset_token_cache()


def _install(monkeypatch, handler) -> list[httpx.Request]:
    """Route the client's transport at ``handler`` and record every request."""
    seen: list[httpx.Request] = []

    def recording(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return handler(request)

    transport = httpx.MockTransport(recording)

    def factory(read_seconds: float, *, follow_redirects: bool = False) -> httpx.Client:
        return httpx.Client(transport=transport, follow_redirects=follow_redirects)

    monkeypatch.setattr(copernicus, "_http_client", factory)
    return seen


def _token_response() -> httpx.Response:
    return httpx.Response(200, json={"access_token": "token-abc", "expires_in": 600})


# --------------------------------------------------------------------------
# Catalogue search
# --------------------------------------------------------------------------


def test_search_filter_hard_locks_the_pipeline_contract(monkeypatch):
    seen = _install(monkeypatch, lambda request: httpx.Response(200, json=_fixture("cdse_search.json")))

    copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)

    query = parse_qs(urlsplit(str(seen[0].url)).query)
    odata_filter = query["$filter"][0]
    assert "att/OData.CSC.StringAttribute/Value eq 'IW_GRDH_1S'" in odata_filter
    assert "att/OData.CSC.StringAttribute/Value eq 'VV&VH'" in odata_filter
    assert "Collection/Name eq 'SENTINEL-1'" in odata_filter
    # Archived products are shown greyed out, never filtered away server-side.
    assert "Online" not in odata_filter


def test_search_percent_encodes_the_polarisation_ampersand(monkeypatch):
    """The classic CDSE integration bug.

    A hand-built query string leaves the '&' in 'VV&VH' literal, the filter
    silently truncates at that character, and every polarisation comes back --
    including the single-pol products the pipeline cannot read.
    """
    seen = _install(monkeypatch, lambda request: httpx.Response(200, json={"value": []}))

    copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)

    raw_query = urlsplit(str(seen[0].url)).query
    assert "VV%26VH" in raw_query
    assert "VV&VH" not in raw_query
    # One '&' per query parameter separator only: $filter, $expand, $orderby, $top.
    assert raw_query.count("&") == 3


def test_search_uses_a_bbox_polygon_of_exactly_four_corners(monkeypatch):
    seen = _install(monkeypatch, lambda request: httpx.Response(200, json={"value": []}))

    copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)

    odata_filter = parse_qs(urlsplit(str(seen[0].url)).query)["$filter"][0]
    assert (
        "POLYGON((79.500000 12.500000,82.500000 12.500000,"
        "82.500000 15.000000,79.500000 15.000000,79.500000 12.500000))"
    ) in odata_filter


def test_search_rejects_products_outside_the_pipeline_contract(monkeypatch):
    """Defence in depth: a provider-side change must not reach the pipeline."""
    _install(monkeypatch, lambda request: httpx.Response(200, json=_fixture("cdse_search.json")))

    results = copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)

    names = [product.name for product in results]
    assert len(results) == 2
    assert all("_IW_GRDH_1SDV_" in name for name in names)
    # The GRDM and the single-pol 1SSV entries in the fixture are dropped.
    assert not any("GRDM" in name for name in names)
    assert not any("1SSV" in name for name in names)


def test_search_keeps_offline_products_visible(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(200, json=_fixture("cdse_search.json")))

    results = copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)

    offline = [product for product in results if not product.online]
    assert len(offline) == 1
    assert offline[0].name.startswith("S1D_IW_GRDH_1SDV_")


def test_search_parses_size_footprint_and_sensing_time(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(200, json=_fixture("cdse_search.json")))

    first = copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)[0]

    assert first.product_id == PRODUCT_ID
    assert first.size_bytes == 1073741824
    assert first.sensing_start == datetime(2026, 7, 2, 0, 30, 56, 123456, tzinfo=timezone.utc)
    assert first.footprint["type"] == "Polygon"
    assert first.online is True


def test_search_maps_throttling_to_a_retryable_error(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(429, text="slow down"))

    with pytest.raises(copernicus.CopernicusUnavailableError):
        copernicus.search_products(bbox=BBOX, start=START, end=END, limit=20)


# --------------------------------------------------------------------------
# Single product lookup
# --------------------------------------------------------------------------


def test_get_product_reads_the_entity_shape(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(200, json=_fixture("cdse_product.json")))

    product = copernicus.get_product(PRODUCT_ID)

    assert product.product_id == PRODUCT_ID
    assert product.product_type == "IW_GRDH_1S"
    assert product.polarisation_channels == "VV&VH"
    assert product.size_bytes == 1073741824


def test_get_product_rejects_a_non_uuid_id(monkeypatch):
    seen = _install(monkeypatch, lambda request: httpx.Response(200, json={}))

    with pytest.raises(copernicus.CopernicusProductNotFoundError):
        copernicus.get_product("../../etc/passwd")

    assert seen == []


def test_get_product_maps_404(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(404, text="not found"))

    with pytest.raises(copernicus.CopernicusProductNotFoundError):
        copernicus.get_product(PRODUCT_ID)


# --------------------------------------------------------------------------
# Token cache
# --------------------------------------------------------------------------


def test_token_is_minted_once_and_reused(monkeypatch):
    seen = _install(monkeypatch, lambda request: _token_response())

    assert copernicus.access_token() == "token-abc"
    assert copernicus.access_token() == "token-abc"

    assert len(seen) == 1
    assert seen[0].url.path.endswith("/token")


def test_token_request_uses_the_client_credentials_grant(monkeypatch):
    seen = _install(monkeypatch, lambda request: _token_response())

    copernicus.access_token()

    body = parse_qs(seen[0].content.decode("utf-8"))
    assert body["grant_type"] == ["client_credentials"]
    assert body["client_id"] == ["test-client"]
    # The password grant must never appear: no account password is handled here.
    assert "username" not in body
    assert "password" not in body


def test_token_expiry_honours_the_refresh_margin(monkeypatch):
    """A token valid for exactly the margin is already treated as expired."""
    monkeypatch.setattr(settings, "COPERNICUS_TOKEN_REFRESH_MARGIN_SECONDS", 60)
    seen = _install(
        monkeypatch,
        lambda request: httpx.Response(200, json={"access_token": "short", "expires_in": 60}),
    )

    clock = {"now": 1000.0}
    monkeypatch.setattr(copernicus.time, "monotonic", lambda: clock["now"])

    assert copernicus.access_token() == "short"
    clock["now"] += 2.0
    copernicus.access_token()

    # 60s lifetime minus a 60s margin clamps to a 1s window, so the second
    # call two seconds later must re-mint rather than serve a stale token.
    assert len(seen) == 2


def test_token_rejection_is_a_permanent_auth_error(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(401, json={"error": "invalid_client"}))

    with pytest.raises(copernicus.CopernicusAuthError):
        copernicus.access_token()


def test_token_server_error_is_retryable(monkeypatch):
    _install(monkeypatch, lambda request: httpx.Response(503, text="maintenance"))

    with pytest.raises(copernicus.CopernicusUnavailableError):
        copernicus.access_token()


def test_missing_credentials_raise_before_any_request(monkeypatch):
    monkeypatch.setattr(settings, "COPERNICUS_CLIENT_SECRET", None)
    seen = _install(monkeypatch, lambda request: _token_response())

    with pytest.raises(RuntimeError):
        copernicus.access_token()

    assert seen == []


# --------------------------------------------------------------------------
# Redirect host allowlist
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("host", "expected"),
    [
        ("dataspace.copernicus.eu", True),
        ("download.dataspace.copernicus.eu", True),
        ("zipper.dataspace.copernicus.eu", True),
        ("DATASPACE.COPERNICUS.EU", True),
        # The whole point of the guard: a suffix-only check would accept this.
        ("dataspace.copernicus.eu.attacker.com", False),
        ("notdataspace.copernicus.eu", False),
        ("attacker.com", False),
        ("", False),
        (None, False),
    ],
)
def test_host_allowlist_matches_exact_or_dotted_suffix_only(host, expected):
    assert copernicus.host_is_allowed(host, ["dataspace.copernicus.eu"]) is expected


def test_download_reattaches_auth_across_an_allowed_redirect(monkeypatch, tmp_path):
    payload = b"SAFE-ARCHIVE-BYTES"

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        if request.url.host == "download.dataspace.copernicus.eu":
            return httpx.Response(
                302,
                headers={"location": "https://zipper.dataspace.copernicus.eu/blob/1"},
            )
        return httpx.Response(200, content=payload)

    seen = _install(monkeypatch, handler)
    destination = tmp_path / "product.zip"

    written = copernicus.download_product_to(PRODUCT_ID, str(destination))

    assert written == len(payload)
    assert destination.read_bytes() == payload
    hops = [request for request in seen if not request.url.path.endswith("/token")]
    assert hops[0].headers.get("authorization") == "Bearer token-abc"
    assert hops[1].url.host == "zipper.dataspace.copernicus.eu"
    assert hops[1].headers.get("authorization") == "Bearer token-abc"


def test_download_strips_auth_for_an_off_domain_redirect(monkeypatch, tmp_path):
    """A lookalike host must receive the request without the bearer token."""

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        if request.url.host == "download.dataspace.copernicus.eu":
            return httpx.Response(
                302,
                headers={"location": "https://dataspace.copernicus.eu.attacker.com/steal"},
            )
        return httpx.Response(200, content=b"decoy")

    seen = _install(monkeypatch, handler)

    copernicus.download_product_to(PRODUCT_ID, str(tmp_path / "product.zip"))

    off_domain = [
        request for request in seen if request.url.host == "dataspace.copernicus.eu.attacker.com"
    ]
    assert len(off_domain) == 1
    assert "authorization" not in {key.lower() for key in off_domain[0].headers}


def test_download_rejects_a_redirect_loop(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "COPERNICUS_MAX_REDIRECTS", 2)

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(
            302, headers={"location": "https://download.dataspace.copernicus.eu/next"}
        )

    _install(monkeypatch, handler)

    with pytest.raises(copernicus.CopernicusRedirectRejectedError):
        copernicus.download_product_to(PRODUCT_ID, str(tmp_path / "product.zip"))


# --------------------------------------------------------------------------
# Download streaming, resume, and failure mapping
# --------------------------------------------------------------------------


def _dropping_content(chunks: list[bytes], drop_after: int):
    def generator():
        for index, chunk in enumerate(chunks):
            if index == drop_after:
                raise httpx.ReadError("connection reset by peer")
            yield chunk

    return generator()


@pytest.fixture
def small_chunks(monkeypatch):
    """Shrink the read chunk so a drop leaves bytes actually on disk.

    ``iter_bytes`` re-chunks and buffers: at the production 1 MiB size a drop
    inside the first megabyte yields nothing at all, so ``written`` stays 0 and
    the retry is a plain restart rather than a resume. That is correct
    behaviour -- we only ever resume from bytes we really wrote -- but it means
    the resume path needs a smaller chunk to be observable in a test.
    """
    monkeypatch.setattr(copernicus, "_DOWNLOAD_CHUNK_BYTES", 10)


def test_download_resumes_with_a_range_header_after_a_drop(monkeypatch, small_chunks, tmp_path):
    full = b"0123456789" * 10
    attempts = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        attempts["count"] += 1
        if attempts["count"] == 1:
            return httpx.Response(200, content=_dropping_content([full[:40], full[40:]], 1))
        start = int(request.headers["range"].removeprefix("bytes=").rstrip("-"))
        return httpx.Response(206, content=full[start:])

    seen = _install(monkeypatch, handler)
    destination = tmp_path / "product.zip"

    written = copernicus.download_product_to(
        PRODUCT_ID, str(destination), expected_size_bytes=len(full)
    )

    assert written == len(full)
    assert destination.read_bytes() == full
    ranged = [request for request in seen if "range" in {k.lower() for k in request.headers}]
    assert ranged and ranged[0].headers["range"] == "bytes=40-"


def test_download_restarts_when_the_server_ignores_the_range(monkeypatch, small_chunks, tmp_path):
    """A 200 answer to a Range request means the whole body is coming again.

    Appending it to the partial file would silently corrupt the archive.
    """
    full = b"ABCDEFGHIJ" * 10
    attempts = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        attempts["count"] += 1
        if attempts["count"] == 1:
            return httpx.Response(200, content=_dropping_content([full[:30], full[30:]], 1))
        return httpx.Response(200, content=full)

    seen = _install(monkeypatch, handler)
    destination = tmp_path / "product.zip"

    written = copernicus.download_product_to(
        PRODUCT_ID, str(destination), expected_size_bytes=len(full)
    )

    # The second request did ask to resume, and the server ignored it.
    ranged = [request for request in seen if "range" in {k.lower() for k in request.headers}]
    assert ranged and ranged[0].headers["range"] == "bytes=30-"
    assert written == len(full)
    assert destination.read_bytes() == full


def test_download_gives_up_after_the_resume_budget(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "COPERNICUS_DOWNLOAD_MAX_RESUMES", 2)

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(200, content=_dropping_content([b"partial"], 0))

    _install(monkeypatch, handler)

    with pytest.raises(copernicus.CopernicusUnavailableError):
        copernicus.download_product_to(PRODUCT_ID, str(tmp_path / "product.zip"))


def test_download_reports_progress(monkeypatch, tmp_path):
    full = b"x" * 2048

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(200, content=full)

    _install(monkeypatch, handler)
    seen: list[tuple[int, int | None]] = []

    copernicus.download_product_to(
        PRODUCT_ID,
        str(tmp_path / "product.zip"),
        expected_size_bytes=len(full),
        progress_callback=lambda written, total: seen.append((written, total)),
    )

    assert seen[-1] == (len(full), len(full))


def test_download_aborts_when_the_caller_says_so(monkeypatch, tmp_path):
    """The worker aborts here when its task lease has been stolen."""

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(200, content=b"y" * 4096)

    _install(monkeypatch, handler)

    with pytest.raises(copernicus.CopernicusAbortedError):
        copernicus.download_product_to(
            PRODUCT_ID, str(tmp_path / "product.zip"), should_abort=lambda: True
        )


def test_download_refreshes_the_token_once_on_401(monkeypatch, tmp_path):
    tokens = {"issued": 0}
    payload = b"recovered"

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            tokens["issued"] += 1
            return httpx.Response(
                200, json={"access_token": f"token-{tokens['issued']}", "expires_in": 600}
            )
        if request.headers.get("authorization") == "Bearer token-1":
            return httpx.Response(401, text="expired")
        return httpx.Response(200, content=payload)

    _install(monkeypatch, handler)
    destination = tmp_path / "product.zip"

    written = copernicus.download_product_to(PRODUCT_ID, str(destination))

    assert written == len(payload)
    assert tokens["issued"] == 2


def test_download_maps_404_to_a_permanent_error(monkeypatch, tmp_path):
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(404, text="gone")

    _install(monkeypatch, handler)

    with pytest.raises(copernicus.CopernicusProductNotFoundError):
        copernicus.download_product_to(PRODUCT_ID, str(tmp_path / "product.zip"))


def test_download_maps_503_to_a_retryable_error(monkeypatch, tmp_path):
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/token"):
            return _token_response()
        return httpx.Response(503, text="busy")

    _install(monkeypatch, handler)

    with pytest.raises(copernicus.CopernicusUnavailableError):
        copernicus.download_product_to(PRODUCT_ID, str(tmp_path / "product.zip"))
